(()=>{
const C={round:4,min:4,max:5,catChance:.25,rise:200,p1:250,p2:300,window:1000,down:200,shake:200,delayRatio:.5};
const S={on:false,scheduled:false,idx:-1,cat:false,tapped:false,used:new Set(),token:0,ids:[]};
const st=document.createElement('style');
st.textContent='.mole-hit-flash::after{content:"";position:absolute;inset:0;border-radius:inherit;background:rgba(220,48,48,.5);pointer-events:none;animation:moleHitFlash .22s ease-out forwards}.mole-stolen{animation:moleTileFade .32s ease-out forwards}.mole-shake{animation:moleTileShake .2s ease-in-out}.mole-stink{position:absolute;right:2px;bottom:4px;font-size:1rem;pointer-events:none;animation:moleStinkRise .9s ease-out forwards}@keyframes moleHitFlash{0%{opacity:1}100%{opacity:0}}@keyframes moleTileFade{0%{opacity:1;transform:scale(1)}100%{opacity:.28;transform:scale(.94)}}@keyframes moleTileShake{0%,100%{transform:translateX(0)}20%{transform:translateX(-4px)}40%{transform:translateX(4px)}60%{transform:translateX(-3px)}80%{transform:translateX(3px)}}@keyframes moleStinkRise{0%{opacity:0;transform:translateY(8px) scale(.9)}20%{opacity:1}100%{opacity:0;transform:translateY(-18px) scale(1.08)}}';document.head.appendChild(st);
function clr(){S.ids.forEach(clearTimeout);S.ids=[]}
function to(fn,ms){const id=setTimeout(()=>{S.ids=S.ids.filter(v=>v!==id);fn()},ms);S.ids.push(id);return id}
function wait(ms){return new Promise(r=>to(r,ms))}
function clean(){moleRunner.classList.remove('show','idle','entering','shaking','exiting');moleRunner.style.transition='none';moleRunner.style.opacity='0';moleRunner.style.pointerEvents='none';moleRunner.style.transform='translate(0,0) scaleX(1)';if(typeof hideDirtStrip==='function')hideDirtStrip(true);if(typeof hideTrapRunner==='function')hideTrapRunner(true)}
function reset(){clr();S.on=false;S.scheduled=false;S.idx=-1;S.cat=false;S.tapped=false;S.used.clear();clean()}
function el(i){return boardEl.children[i]||null}
function pool(wantCat){const a=[];for(let i=0;i<tiles.length;i++){const t=tiles[i];if(!t||t.isEmpty||t.state!=='idle'||S.used.has(i))continue;if(!!t.isCat===wantCat)a.push(i)}return a}
function pick(){const wantCat=Math.random()<C.catChance;let a=pool(wantCat);if(!a.length)a=pool(!wantCat);if(!a.length)return-1;const i=a[Math.floor(Math.random()*a.length)];S.cat=!!tiles[i]?.isCat;S.used.add(i);return i}
function place(i){const b=el(i);if(!b)return null;const w=boardWrapEl.getBoundingClientRect(),r=b.getBoundingClientRect(),size=Math.min(r.width*.9,82),left=r.left-w.left+r.width/2-size/2,bottom=w.bottom-r.bottom;moleRunner.style.left=`${left}px`;moleRunner.style.bottom=`${Math.max(0,bottom)}px`;moleRunner.style.width=`${size}px`;moleRunner.style.transform='translateY(62%) scaleX(1)';moleRunner.style.opacity='1';moleRunner.style.pointerEvents='none';moleRunner.classList.add('show');return b}
function hit(i){const b=el(i);if(!b)return;b.classList.remove('mole-hit-flash');void b.offsetWidth;b.classList.add('mole-hit-flash');to(()=>b.classList.remove('mole-hit-flash'),260)}
function stink(i){const b=el(i);if(!b)return;b.style.position='relative';const n=document.createElement('span');n.className='mole-stink';n.textContent='🦨';b.appendChild(n);to(()=>n.remove(),950)}
function steal(i){const t=tiles[i],b=el(i);if(!t||!b)return;t.selected=false;t.state='stolen';moleCatsLostThisRound+=1;b.classList.remove('selected');b.classList.add('mole-shake');if(typeof updatePickedCount==='function')updatePickedCount();to(()=>{b.classList.remove('mole-shake');b.classList.add('mole-stolen');stink(i)},C.shake)}
async function down(hitOk){moleRunner.style.pointerEvents='none';moleRunner.style.transition=`transform ${C.down}ms ease, opacity ${C.down}ms ease`;moleRunner.style.transform=`translateY(62%) scaleX(${hitOk?1:-1})`;moleRunner.style.opacity='0';await wait(C.down);clean()}
async function pop(tok){if(tok!==S.token||reviewInProgress||gameOver||remainingTime<=0)return false;const i=pick();if(i===-1)return false;S.idx=i;S.tapped=false;if(!place(i))return false;moleRunner.style.transition=`transform ${C.rise}ms ease`;void moleRunner.offsetWidth;moleRunner.style.transform='translateY(0%) scaleX(1)';await wait(C.rise);if(tok!==S.token||reviewInProgress||gameOver||remainingTime<=0)return false;await wait(C.p1);if(S.tapped){hit(i);await down(true);return true}moleRunner.style.transition='transform 120ms ease';moleRunner.style.transform='translateY(0%) scaleX(-1)';await wait(120);await wait(C.p2);if(S.tapped){hit(i);await down(true);return true}moleRunner.style.transition='transform 120ms ease';moleRunner.style.transform='translateY(0%) scaleX(1)';await wait(120);moleRunner.style.pointerEvents='auto';await wait(C.window);if(S.tapped){hit(i);await down(true);return true}if(S.cat){steal(i);await down(false);return true}await down(false);return true}
async function start(tok){if(S.on||round<C.round||reviewInProgress||gameOver)return;S.on=true;S.scheduled=false;S.used.clear();const n=randomIntBetween(C.min,C.max);for(let k=0;k<n;k++){if(tok!==S.token||reviewInProgress||gameOver||remainingTime<=0)break;const ok=await pop(tok);if(!ok)break;await wait(120)}S.on=false;S.idx=-1;S.cat=false;S.tapped=false;clean()}
function schedule(){if(round<C.round||S.scheduled)return;S.scheduled=true;S.token+=1;const tok=S.token,delay=Math.max(900,Math.round(roundTime*1000*C.delayRatio));to(()=>{if(tok!==S.token)return;start(tok)},delay)}
const ob=beginRound;beginRound=async function(...a){reset();const r=await ob.apply(this,a);schedule();return r};
const oh=showHomeScreen;showHomeScreen=function(...a){reset();return oh.apply(this,a)};
const os=startReview;startReview=async function(...a){reset();return os.apply(this,a)};
moleRunner.addEventListener('click',e=>{if(!S.on)return;e.preventDefault();e.stopPropagation();S.tapped=true},true);
reset();
})();
